name: build-ics

on:
  push:

permissions:
  contents: write

jobs:
  build-ics:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Generate ICS files
        run: python scripts/build_ics.py

      - uses: stefanzweifel/git-auto-commit-action@v7
